# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0.0


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-linux:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # See available images in: 
      # https://circleci.com/developer/images
      - image: cimg/openjdk:21.0.0

    working_directory: ~/repo
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: test
          command: ./gradlew test

  test-win:
    executor: win/default
    working_directory: ~/repo
    steps:
      # It doesn't work out of the box on windows machine, like in: 
      #   https://discuss.circleci.com/t/empty-checkout-key-on-windows-pipeline-only/47116
      # the workaround (proposed also in the circleCI discuss forum) seems to be adding by hand a ssh keys which
      # is not automatically added even if it should be supposed to be, see also: 
      #   https://circleci.com/docs/add-ssh-key/
      - add_ssh_keys:
            fingerprints:
              - "10:84:29:02:f1:90:0b:2a:b0:09:2f:55:bf:3c:80:df"
              - "ed:47:21:a0:f3:08:aa:06:c5:e2:62:d8:e4:d4:79:71"
      - checkout
      - run:
          name: test
          shell: bash.exe
          command: ./gradlew.bat test

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
   test:
    jobs:
      - test-linux
      - test-win
